# This rule is not used by the project logger-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over logger.logger.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: logger-controller
    app.kubernetes.io/managed-by: kustomize
  name: logger-admin-role
rules:
- apiGroups:
  - logger.logger.com
  resources:
  - loggers
  verbs:
  - '*'
- apiGroups:
  - logger.logger.com
  resources:
  - loggers/status
  verbs:
  - get
